import React from "react";

interface ILoading {

}

const Loading: React.FC<ILoading> = ({}): JSX.Element => {
    return (
        <div className="flex justify-center items-center flex-col fixed top-0 left-0 w-screen h-screen bg-[rgba(255,255,255,.5)] z-[1000]">
            <svg
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                width="200px"
                height="200px"
                viewBox="0 0 100 100"
                preserveAspectRatio="xMidYMid"
            >
                <circle cx={50} cy={50} r={0} fill="none" stroke="#1d3f72" strokeWidth={2}>
                    <animate
                        attributeName="r"
                        repeatCount="indefinite"
                        dur="1s"
                        values="0;40"
                        keyTimes="0;1"
                        keySplines="0 0.2 0.8 1"
                        calcMode="spline"
                        begin="0s"
                    />
                    <animate
                        attributeName="opacity"
                        repeatCount="indefinite"
                        dur="1s"
                        values="1;0"
                        keyTimes="0;1"
                        keySplines="0.2 0 0.8 1"
                        calcMode="spline"
                        begin="0s"
                    />
                </circle>
                <circle cx={50} cy={50} r={0} fill="none" stroke="#5699d2" strokeWidth={2}>
                    <animate
                        attributeName="r"
                        repeatCount="indefinite"
                        dur="1s"
                        values="0;40"
                        keyTimes="0;1"
                        keySplines="0 0.2 0.8 1"
                        calcMode="spline"
                        begin="-0.5s"
                    />
                    <animate
                        attributeName="opacity"
                        repeatCount="indefinite"
                        dur="1s"
                        values="1;0"
                        keyTimes="0;1"
                        keySplines="0.2 0 0.8 1"
                        calcMode="spline"
                        begin="-0.5s"
                    />
                </circle>
                {/* [ldio] generated by https://loading.io/ */}
            </svg>
        </div>
    );
}

export default Loading;